export const exampleData = [
  {
    name: "Sweden",
    nativeName: "Sverige",
    population: 10353442,
    region: "Europe",
    subRegion: "Northern Europe",
    capital: "Stockholm",
    topLevelDomain: [".se"],
    currencies: [{ name: "Swedish krona", symbol: "kr" }],
    languages: ["Swedish"],
    borders: ["Norway", "Finland", "Denmark"],
    flag: "https://flagcdn.com/se.svg",
  },
  {
    name: "Brazil",
    nativeName: "Brasil",
    population: 213993437,
    region: "Americas",
    subRegion: "South America",
    capital: "Brasília",
    topLevelDomain: [".br"],
    currencies: [{ name: "Brazilian real", symbol: "R$" }],
    languages: ["Portuguese"],
    borders: [], // Brazil has no borders in this example
    flag: "https://flagcdn.com/br.svg",
  },
  {
    name: "Japan",
    nativeName: "日本",
    population: 125960000,
    region: "Asia",
    subRegion: "Eastern Asia",
    capital: "Tokyo",
    topLevelDomain: [".jp"],
    currencies: [{ name: "Japanese yen", symbol: "¥" }],
    languages: ["Japanese"],
    borders: [], // Japan is an island nation with no borders
    flag: "https://flagcdn.com/jp.svg",
  },
  {
    name: "Norway",
    nativeName: "Norge",
    population: 5379475,
    region: "Europe",
    subRegion: "Northern Europe",
    capital: "Oslo",
    topLevelDomain: [".no"],
    currencies: [{ name: "Norwegian krone", symbol: "kr" }],
    languages: ["Norwegian"],
    borders: ["Sweden", "Finland"],
    flag: "https://flagcdn.com/no.svg",
  },
  {
    name: "Finland",
    nativeName: "Suomi",
    population: 5527573,
    region: "Europe",
    subRegion: "Northern Europe",
    capital: "Helsinki",
    topLevelDomain: [".fi"],
    currencies: [{ name: "Euro", symbol: "€" }],
    languages: ["Finnish", "Swedish"],
    borders: ["Sweden", "Norway", "Russia"],
    flag: "https://flagcdn.com/fi.svg",
  },
];